// scripts/gen_version.js
// package.json の version を src/version.js に書き出す。
// build パイプラインの先頭で実行することで、RicDOM.version / RicUI.version
// がリリース時に package.json 以外を手で更新しなくても自動で追従する。

'use strict';

const fs = require('fs');
const path = require('path');

const pkg = require(path.join(__dirname, '..', 'package.json'));
const out = `// Auto-generated by scripts/gen_version.js.
// Do NOT edit this file manually. Update package.json and run 'npm run build'.
'use strict';
module.exports = ${JSON.stringify(pkg.version)};
`;

const target = path.join(__dirname, '..', 'src', 'version.js');
fs.writeFileSync(target, out);
console.log(`[gen_version] src/version.js -> ${pkg.version}`);
